### ISSUE TITLE
changing resolution not working

### ISSUE THREAD

**Issue by amarantsnipersnake** [masagrator/ToCS1-ENX#4]
i just want to lower a little bit the resolution but after i choose my desired resolution. description said that will need to restart, after restaring the game. it coming back to default 720p. am i doing something here?

**Comment by MyNinjaPenguin** [comment]
Same here. I checked in the "config" folder, and no "subsdk9.save" file exists, and no options are saving from the secret menu.

**Comment by masagrator** [comment]
It was fixed with 1.2 Plugin fix
